### ISSUE TITLE
Stable url for solver lists

### ISSUE THREAD

**Issue by blegat** [jump-dev/jump-dev.github.io#60]
I constantly use hyperlinks to the list of solvers in the JuMP doc and I often need to update them because the JuMP doc is refactored.
Wouldn't it be useful to have link like `jump.dev/solvers` that redirects to the right place so that we just need to change where this links redirect to ?

**Comment by odow** [comment]
@mlubin might be able to modify the DNS settings so that `solvers.jump.dev` redirects to https://jump.dev/JuMP.jl/stable/installation/#Supported-solvers

When was the last time that the link changed? I've been trying to avoid changing the link.

**Comment by odow** [comment]
We can probably also just add a new page with a redirection: 
https://github.com/JuliaOpt/juliaopt.github.io/blob/master/JuMP.jl/v0.21.1/index.html

**Comment by blegat** [comment]
I have:
* In SumOfSquares: https://jump.dev/JuMP.jl/v0.21.6/installation/#Supported-solvers
* In SwitchOnSafety: http://jump.dev/JuMP.jl/v0.21.3/installation/#Getting-Solvers-1
* In Polyhedra: https://jump.dev/JuMP.jl/stable/installation/#Getting-Solvers-1

As you can see, it's a mess ^^

**Comment by odow** [comment]
We seem to be getting on okay without this. And a future version of Documenter is going to support better cross-linking of documentation packages: https://github.com/JuliaDocs/Documenter.jl/pull/2424
